cd E:\sdk\vc7\mapserver
svn cleanup
cd E:\sdk\vc7\msautotest
svn cleanup
cd E:\sdk\vc7\mapserver-6-0
svn cleanup
cd E:\sdk\vc7\msautotest-6-0
svn cleanup
cd E:\sdk\vc7\gdal-trunk
svn cleanup
cd E:\sdk\vc7\gdal-1.8
svn cleanup

cd E:\sdk\vc8\mapserver
svn cleanup
cd E:\sdk\vc8\msautotest
svn cleanup
cd E:\sdk\vc8\mapserver-6-0
svn cleanup
cd E:\sdk\vc8\msautotest-6-0
svn cleanup
cd E:\sdk\vc8\gdal-trunk
svn cleanup
cd E:\sdk\vc8\gdal-1.8
svn cleanup

cd E:\sdk\vc8x64\mapserver
svn cleanup
cd E:\sdk\vc8x64\msautotest
svn cleanup
cd E:\sdk\vc8x64\mapserver-6-0
svn cleanup
cd E:\sdk\vc8x64\msautotest-6-0
svn cleanup
cd E:\sdk\vc8x64\gdal-trunk
svn cleanup
cd E:\sdk\vc8x64\gdal-1.8
svn cleanup

cd E:\sdk\vc9\mapserver
svn cleanup
cd E:\sdk\vc9\msautotest
svn cleanup
cd E:\sdk\vc9\mapserver-6-0
svn cleanup
cd E:\sdk\vc9\msautotest-6-0
svn cleanup
cd E:\sdk\vc9\gdal-trunk
svn cleanup
cd E:\sdk\vc9\gdal-1.8
svn cleanup

cd E:\sdk\vc9x64\mapserver
svn cleanup
cd E:\sdk\vc9x64\msautotest
svn cleanup
cd E:\sdk\vc9x64\mapserver-6-0
svn cleanup
cd E:\sdk\vc9x64\msautotest-6-0
svn cleanup
cd E:\sdk\vc9x64\gdal-trunk
svn cleanup
cd E:\sdk\vc9x64\gdal-1.8
svn cleanup

cd E:\sdk\vc10\mapserver
svn cleanup
cd E:\sdk\vc10\msautotest
svn cleanup
cd E:\sdk\vc10\mapserver-6-0
svn cleanup
cd E:\sdk\vc10\msautotest-6-0
svn cleanup
cd E:\sdk\vc10\gdal-trunk
svn cleanup
cd E:\sdk\vc10\gdal-1.8
svn cleanup

cd E:\sdk\vc10x64\mapserver
svn cleanup
cd E:\sdk\vc10x64\msautotest
svn cleanup
cd E:\sdk\vc10x64\mapserver-6-0
svn cleanup
cd E:\sdk\vc10x64\msautotest-6-0
svn cleanup
cd E:\sdk\vc10x64\gdal-trunk
svn cleanup
cd E:\sdk\vc10x64\gdal-1.8
svn cleanup

cd e:\builds