cd E:\sdk\vc9\mapserver
git clean
cd E:\sdk\vc9\msautotest
svn cleanup
cd E:\sdk\vc9\mapserver-7-0
git clean
cd E:\sdk\vc9\msautotest-7-0
git clean
cd E:\sdk\vc9\gdal-trunk
svn cleanup
cd E:\sdk\vc9\gdal-2.2
svn cleanup

cd E:\sdk\vc9x64\mapserver
git clean
cd E:\sdk\vc9x64\msautotest
git clean
cd E:\sdk\vc9x64\mapserver-7-0
git clean
cd E:\sdk\vc9x64\msautotest-7-0
git clean
cd E:\sdk\vc9x64\gdal-trunk
svn cleanup
cd E:\sdk\vc9x64\gdal-2.2
svn cleanup

cd E:\sdk\vc10\mapserver
git clean
cd E:\sdk\vc10\msautotest
git clean
cd E:\sdk\vc10\mapserver-7-0
git clean
cd E:\sdk\vc10\msautotest-7-0
git clean
cd E:\sdk\vc10\gdal-trunk
svn cleanup
cd E:\sdk\vc10\gdal-2.2
svn cleanup

cd E:\sdk\vc10x64\mapserver
git clean
cd E:\sdk\vc10x64\msautotest
git clean
cd E:\sdk\vc10x64\mapserver-7-0
git clean
cd E:\sdk\vc10x64\msautotest-7-0
git clean
cd E:\sdk\vc10x64\gdal-trunk
svn cleanup
cd E:\sdk\vc10x64\gdal-2.2
svn cleanup

cd E:\sdk\vc11\mapserver
git clean
cd E:\sdk\vc11\\msautotest
git clean
cd E:\sdk\vc11\\mapserver-7-0
git clean
cd E:\sdk\vc11\msautotest-7-0
git clean
cd E:\sdk\vc11\gdal-trunk
svn cleanup
cd E:\sdk\vc11\gdal-2.2
svn cleanup

cd E:\sdk\vc11x64\mapserver
git clean
cd E:\sdk\vc11x64\msautotest
git clean
cd E:\sdk\vc11x64\mapserver-7-0
git clean
cd E:\sdk\vc11x64\msautotest-7-0
git clean
cd E:\sdk\vc11x64\gdal-trunk
svn cleanup
cd E:\sdk\vc11x64\gdal-2.2
svn cleanup

cd E:\sdk\vc12\mapserver
git clean
cd E:\sdk\vc12\msautotest
git clean
cd E:\sdk\vc12\mapserver-7-0
git clean
cd E:\sdk\vc12\msautotest-7-0
git clean
cd E:\sdk\vc12\gdal-trunk
svn cleanup
cd E:\sdk\vc12\gdal-2.2
svn cleanup

cd E:\sdk\vc12x64\mapserver
git clean
cd E:\sdk\vc12x64\msautotest
git clean
cd E:\sdk\vc12x64\mapserver-7-0
git clean
cd E:\sdk\vc12x64\msautotest-7-0
git clean
cd E:\sdk\vc12x64\gdal-trunk
svn cleanup
cd E:\sdk\vc12x64\gdal-2.2
svn cleanup

cd E:\sdk\vc14\mapserver
git clean
cd E:\sdk\vc14\msautotest
git clean
cd E:\sdk\vc14\mapserver-7-0
git clean
cd E:\sdk\vc14\msautotest-7-0
git clean
cd E:\sdk\vc14\gdal-trunk
svn cleanup
cd E:\sdk\vc14\gdal-2.2
svn cleanup

cd E:\sdk\vc14x64\mapserver
git clean
cd E:\sdk\vc14x64\msautotest
git clean
cd E:\sdk\vc14x64\mapserver-7-0
git clean
cd E:\sdk\vc14x64\msautotest-7-0
git clean
cd E:\sdk\vc14x64\gdal-trunk
svn cleanup
cd E:\sdk\vc14x64\gdal-2.2
svn cleanup

cd E:\sdk\vc15\mapserver
git clean
cd E:\sdk\vc15\msautotest
git clean
cd E:\sdk\vc15\mapserver-7-0
git clean
cd E:\sdk\vc15\msautotest-7-0
git clean
cd E:\sdk\vc15\gdal-trunk
svn cleanup
cd E:\sdk\vc15\gdal-2.2
svn cleanup

cd E:\sdk\vc15x64\mapserver
git clean
cd E:\sdk\vc15x64\msautotest
git clean
cd E:\sdk\vc15x64\mapserver-7-0
git clean
cd E:\sdk\vc15x64\msautotest-7-0
git clean
cd E:\sdk\vc15x64\gdal-trunk
svn cleanup
cd E:\sdk\vc15x64\gdal-2.2
svn cleanup

cd e:\builds